---

- hosts: webserver,vagrant-drupal
  become: yes
  vars_files:
    - vars/main.yml

  roles:
    - geerlingguy.mysql
    - geerlingguy.apache
    - geerlingguy.php-versions
    - geerlingguy.php
    - geerlingguy.php-mysql
    - geerlingguy.composer
    - geerlingguy.drush
    - geerlingguy.drupal
