---

- hosts: webserver,vagrant-drupal
  become: yes
  vars_files:
    - vars/main.yml

  tasks:
    - name: set owner vagrant:www-data for "{{ drupal_composer_install_dir }}"
      ansible.builtin.file:
        path: "{{ drupal_composer_install_dir }}"
        state: directory
        recurse: yes
        owner: vagrant
        group: www-data
      become: yes  

  roles:
    - geerlingguy.mysql
    - geerlingguy.apache
    - geerlingguy.php-versions
    - geerlingguy.php
    - geerlingguy.php-mysql
    - geerlingguy.composer
    - geerlingguy.drush
    - geerlingguy.drupal
