---
- hosts: webserver,vagrant-drupal
  vars_files:
    - vars/main.yml

  tasks:
    - name: set owner vagrant for "{{ drupal_composer_install_dir }}"
      ansible.builtin.file:
        path: "{{ drupal_composer_install_dir }}"
        state: directory
        recurse: yes
        owner: vagrant
      become: yes

